### ISSUE TITLE
Code example on vanilla JavaScript (ES6+)

### ISSUE THREAD

**Issue by igolskyi** [taskforcesh/bullmq-mailbot#1]
Hi, thanks for the good tutorial and code example for using BullMQ. Since I do not currently use Typescript for my project, I rewrote the first part of the manual code in vanilla JavaScript. Would it be useful for the BullMQ team to have a complete code example on JS? If so, I could make a full port. Now there is only the first part, which is available here: [bullmq-mailbot-js](https://github.com/igolskyi/bullmq-mailbot-js).

**Comment by manast** [comment]
Thanks, it looks really good. I am not sure how many users are out there still using plain JS, I wish more did just use typescript since it eliminates so many common mistakes. So feel free to add the rest of the parts if you feel like it, I can update the blog post with a reference to these repo for JS users.

**Comment by igolskyi** [comment]
Ok, good idea. Then soon, when the code is completed, I will let you know.

**Comment by igolskyi** [comment]
Hi @manast , as agreed earlier, I finished a port of the tutorial's code (all 3 parts - every part is located on a different branch) to vanilla JavaScript. You can view it, and if all goes well, I would appreciate the publication of the link in the tutorial to the JavaScript version.

**Comment by manast** [comment]
Thanks, looks great. Just one comment, I am surprised you used "required" instead of "import". I have updated the blog posts to link to your repo.

**Comment by igolskyi** [comment]
Thanks. Yes, "import" have some [differences](https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_differences_between_es_modules_and_commonjs) with "require",  I will update from "require" to "import" in the future.
